version: "3.3"

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_DB: SalesApiDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - evaluation-network

  sales-api:
    image: sales-api
    build:
      context: src/SalesApi
      dockerfile: SalesApi.Presentation/Dockerfile
    container_name: sales-api
    depends_on:
      - db
    ports:
      - "8090:8090"
    environment:
      - ConnectionStrings__SalesApiDb=Host=db;Database=SalesApiDb;Username=postgres;Password=admin
    networks:
      - evaluation-network
    tty: true

  gateway:
    image: ocelot-gateway
    build:
      context: src/Gateway
      dockerfile: Gateway.Api/Dockerfile
    container_name: ocelot-gateway
    ports:
      - "0.0.0.0:7777:7777"
    environment:
      - ASPNETCORE_URLS=http://+:7777
    depends_on:
      - sales-api
    networks:
      - evaluation-network

networks:
  evaluation-network:
    external: false
